const Items = [
  {
    id: 1,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720927046/KalaiPortfolio/kthmxgnidlhy0unadfny.png",
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "CRUD operations (Story create, read, update and delete)",
      "Home",
      "About",
      "User",
      "Admin",
      "A user can order through the Admin for CRUD Website services, to manage the user booking details and payment control.",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "TailwindCSS",
      "React toastify",
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Stripe Integration"
    ],
    title: "Vehicle Reservation Systems",
    description:
      "The Vehicle Reservation System is a comprehensive web application developed using the MERN (MongoDB, Express.js, React, Node.js) stack. This system is designed to streamline the process of reserving vehicles, offering both user and admin functionalities to enhance the user experience and system management.The Admin also access the stripe dashboard to create a invoice for the bookings",
    category: "personal",
    codeLink: "https://github.com/kalaiyarasumr/Vehicle-Reservation-System/blob/main/Vehicle%20Reservation%20Systems.zip",
  },
  {
    id: 2,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720929232/KalaiPortfolio/fd2ly1aocurundzvztoi.png",
    features: [
     " User Registration and Login: Secure authentication system enabling users to create accounts and log in.",
      "Music Streaming: High-quality streaming of music tracks, offering a seamless listening experience.",
      "Search and Discover: Advanced search functionality to find specific songs, artists, or albums. Discover new music through curated playlists and recommendations.",
       "Playlist Management: Users can create, edit, and delete custom playlists.",
      "Favorites: Users can mark tracks as favorites for easy access.",
      "User Profile: Manage personal information and view listening history.",
       "Admin Panel: Administrators can manage the music library, including adding, updating, or deleting tracks."
    ],
    technologies: [
          "React.js",
          "Redux.",
           "CSS/SCSS",
           "Node.js",
           "Express.js",
    ],
    title: "Music Application Service",
    description:
      "The Music Application Service is a dynamic and interactive web application developed using React for the frontend and Node.js with Express for the backend. This platform allows users to explore, stream, and manage their favorite music tracks. The service provides a rich user experience with a seamless interface, allowing users to discover new music, create playlists, and manage their music library effectively.",
    category: "personal",
    codeLink: "https://github.com/kalaiyarasumr/Music-Streaming-Service/tree/main/Audio",
  },
  {
    id: 3,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720929258/KalaiPortfolio/l0gontzncgqz9d4xpyum.png",
    features: [
      "Data Integration",
      "Descriptive Analytics",
      "Predictive Analytics",
      "Customer Segmentation",
      "Market Basket Analysis",
      "Report Generation",
    ],
    technologies: [
      "Data Analytics Platform: RapidMiner",
      "Data Sources: Walmart sales data, Customer transaction records, Product information databases",
      "Data Processing: Data Cleaning, Data Transformation",
      "Modeling Techniques: Regression Analysis, Classification, Clustering, Association Rule Mining",
      "Visualization: RapidMiner Visualization",
    ],
    title: "Walmart Product Analysis",
    description:
      "The Walmart Product Analysis project leverages RapidMiner to perform comprehensive data analysis on Walmart's product sales data. The project aims to uncover valuable insights into product performance, customer preferences, and sales trends. By utilizing data mining techniques and advanced analytics, this project provides actionable recommendations to improve inventory management, pricing strategies, and overall sales performance for Walmart.",
    category: "personal",
    codeLink: "https://github.com/kalaiyarasumr/WalmartProductAnalysis",
  },
  {
    id: 4,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720934243/KalaiPortfolio/mnb9xgiglyrzomh1uogc.png",
    features: [
      "Real-time traffic monitoring",
      "User behavior analysis",
      "Traffic source segmentation",
      "Page view tracking",
      "Bounce rate analysis",
      "Customizable dashboards",
      "Interactive visualizations",
      "Trend analysis",
      "Reporting and sharing capabilities",
    ],
    technologies: [
     "Data Analytics Platform: Power BI",
     "Data Sources: Web analytics tools (e.g., kaggle), Website server logs",
     "Data Processing: Data Cleaning, Data Transformation",
     "Visualization: Power BI Visualizations, Custom Dashboards",
     "Reporting: Scheduled Reports, Interactive Reports",
            
    ],
    title: "Website Traffic Analaysis",
    description:
      "The Website Traffic Analysis project utilizes Power BI to monitor and analyze website traffic data. This project aims to provide insights into user behavior, traffic sources, and engagement metrics. By leveraging Power BI's powerful data visualization and reporting capabilities, the project helps stakeholders understand website performance and make data-driven decisions to enhance user experience and optimize marketing strategies..",
    category: "personal",
    codeLink: "https://github.com/kalaiyarasumr/Web-Marketing-analysis",
  },
  {
    id: 5,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720937299/KalaiPortfolio/umusn70xyaya49gjd0fv.png",
    features: [
      "User-friendly interface for data input",
      "Historical sales data visualization",
      "Machine learning model for sales prediction",
      "Real-time prediction updates",
      "Interactive graphs and charts",
      "Exportable prediction reports",
      "Customizable prediction parameters",
      "Data preprocessing and cleaning tools",
      "Responsive design for various devices",
    ],
    technologies: [
      "Backend: Python",
      "Machine Learning: Jupyter Notebook, Scikit-learn, Pandas, NumPy",
      "Frontend: HTML, CSS",
      "Visualization: Matplotlib, Seaborn",
      "Data Handling: CSV, Excel integration",
    ],
    title: "Sales Prediction Web Applications",
    description:
      "The Sales Prediction Web Application leverages machine learning algorithms to predict future sales based on historical data. Built with Jupyter Notebook for model development, Python for backend processing, and HTML and CSS for frontend presentation, this application aims to provide businesses with accurate sales forecasts to help in inventory management, marketing strategy, and financial planning.",
    category: "personal",
    codeLink: "https://github.com/kalaiyarasumr/Codesoft-intern/tree/main/Task-1",
  },
  {
    id: 6,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720936771/KalaiPortfolio/uuhbgswd7uqykpvwbotr.png",
    features: [
      "Mobile Responsive",
      "Beautiful Animations",
      "Rapid Controls",
      "High Score",
      "Mario Background Music",
      "Jump & Game Over Sound Effect",
    ],
    technologies: [
      "React",
      "CSS",
      "React Hooks",
      "React Router",
      "React Redux",
    ],
    title: "Mario Jump",
    description:
      "Mario Jump is an endless running game inspired by the famous Google Chrome's T-Rex Dinosaur Game 🦖. The game is built entirely with ReactJS ⚛ and Redux Toolkit 🔧.",
    category: "game",
    codeLink: "https://github.com/kalaiyarasumr/Mario-Game-Jumpo/tree/main/Mario-game-jump",
  },
  {
    id: 7,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720938017/KalaiPortfolio/z85gkn764xrghcewgzkm.png",
    features: [
      "User-friendly interface with a modern aesthetic",
      "Intuitive navigation for browsing music and playlists",
      "Playlist creation and management",
      "User profile customization",
      "Search functionality for songs, albums, and artists",
      "Responsive design for various devices",
      "Interactive wireframes to demonstrate user flow",
      "Dark and light mode options",
    ],
    technologies: [
      "Design Tool: Figma",
      "Wireframing: Figma's wireframing tools",
      "Prototyping: Figma interactive prototypes",
      "Collaboration: Figma team collaboration features",
      "Design System: Component libraries and reusable design elements in Figma",
    ],
    title: "Music App Design",
    description:
      "The Music App Design project focuses on creating an intuitive and visually appealing user interface for a music streaming application. Utilizing Figma for design and wireframing, the project aims to enhance user experience by ensuring easy navigation, aesthetic appeal, and functionality. The design includes screens for browsing music, creating playlists, and user profile management.",
    category: "personal",
    codeLink: "https://github.com/kalaiyarasumr/FigmaDesigns/blob/main/music%20app%20design.fig",
  },
  {
    id: 8,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720939694/KalaiPortfolio/ffctmbjqozqxynznnbpb.png",
    features: [
      "Homepage",
      "Project Showcase",
      "Skills Section",
      "About Me",
      "Contact Form",
      "Responsive Design",
      "Smooth Animations",
      "Interactive Elements",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Form Handling",
    ],
    title: "Personal Portfolio",
    description:
      "The Personal Portfolio project showcases a developer's skills, projects, and professional background using a sleek and modern design. Built with HTML, CSS, and JavaScript, this portfolio aims to provide a comprehensive overview of the developer's expertise and accomplishments, allowing potential employers and clients to easily navigate and view their work.",
    category: "personal",
    codeLink: "https://github.com/kalaiyarasumr/PersonalPortfolio",
  },
  {
    id: 9,
    mainImage: "https://res.cloudinary.com/dsjvzfp94/image/upload/v1720940835/KalaiPortfolio/rrv5ikzlbkrihyp3eyin.png",
    features: [
      "Visual representation of sorting algorithms",
      "Interactive controls for starting, pausing, and resetting the visualization",
      "Display of algorithm steps and comparisons in real-time",
      "Different sorting algorithms (e.g., Bubble Sort, Selection Sort, Merge Sort,Quick Sort,Heap Sort)",
      "Color-coded visualization for better understanding",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
    ],
    title: "Algorithms Sorting Visualizer",
    description:
      "Algorithm Sorting Visualizer is a web application that provides a visual representation of various sorting algorithms, allowing users to interactively observe and understand how each algorithm works in sorting data.",
    category: "game",
    codeLink: "https://github.com/kalaiyarasumr/Algorithms-Sorting-Visualizer/tree/main/SortingAlgo-master",
  },
];

export default Items;